version: '3.8'

#Banco de dados PostGres com dados dos clientes
services:
  db:
    image: postgres:15
    container_name: postgresBD
    environment:
      POSTGRES_USER: ${POSTGRES_USER_DB1}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_DB1}
      POSTGRES_DB: ${POSTGRES_DB_DB1}
    ports:
      - "${POSTGRES_PORT_DB1}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

#Banco de dados Postgres
  postgres:
    container_name: evolutionDB
    image: postgres:15
    networks:
      - evolution-net
    command: ["postgres", "-c", "max_connections=1000"]
    restart: always
    ports:
      - "${POSTGRES_PORT_DB2}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER_DB2}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_DB2}
      - POSTGRES_DB=${POSTGRES_DB_DB2}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432

#Postgres Admin
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: evolutionPGA
    networks:
      - evolution-net
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL_PGA1}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD_PGA1}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT_PGA1}:80"
    links:
      - postgres
    restart: always

#Banco de dados Redis
  redis:
    image: redis:latest
    networks:
      - evolution-net
    container_name: evolutionrRedis
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_redis:/data
    ports:
      - "${REDIS_PORT}:6379"

#Framework EvolutionAPI 
  evolution-api:
      container_name: evolutionAPI
      image: atendai/evolution-api:latest
      restart: always
      networks:
        - evolution-net
      ports:
        - "${EVOLUTION_PORT}:8080"
      depends_on:
        - postgres
        - redis
      env_file:
        - .env
      volumes:
        - evolution_instances:/evolution/instances

volumes:
  postgres_data:
  pgadmin_data:
  evolution_redis:
  evolution_instances:
  pgdata:

networks:
  evolution-net:
    external: true