version: '3.8'

#Banco de dados PostGres com dados dos clientes
services:
  db:
    image: postgres:15
    container_name: postgresBD
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: DB_Cobranca
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

#Banco de dados Postgres
  postgres:
    container_name: evolutionDB
    image: postgres:15
    networks:
      - evolution-net
    command: ["postgres", "-c", "max_connections=1000"]
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=DB_evolution
      - POSTGRES_PASSWORD=db123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
#Postgres Admin
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: evolutionPGA
    networks:
      - evolution-net
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin
      - PGADMIN_DEFAULT_PASSWORD=admin123
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - 4000:80
    links:
      - postgres

#Banco de dados Redis
  redis:
    image: redis:latest
    networks:
      - evolution-net
    container_name: evolutionrRedis
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_redis:/data
    ports:
      - 6379:6379

#Framework EvolutionAPI 
  evolution-api:
      container_name: evolutionAPI
      image: atendai/evolution-api:v2.1.1
      restart: always
      networks:
        - evolution-net
      ports:
        - "8080:8080"
      depends_on:
        - postgres
        - redis
      env_file:
        - .env
      volumes:
        - evolution_instances:/evolution/instances

volumes:
  postgres_data:
  pgadmin_data:
  evolution_redis:
  evolution_instances:
  pgdata:

networks:
  evolution-net:
    external: true